### ISSUE TITLE
Homework_11.03_navigation_drawer @kulebin

### ISSUE THREAD

**Issue by wanderer005** [DzmitrySlutskiy/EpamTraining2019#103]
HW 11.03
[https://github.com/DzmitrySlutskiy/EpamTraining2019/pull/102](https://github.com/DzmitrySlutskiy/EpamTraining2019/pull/102)

@kulebin

**Comment by ilya-shknaj** [comment]
@wanderer005 Ok, Please fix just one comment

**Comment by wanderer005** [comment]
Fixed
[https://github.com/DzmitrySlutskiy/EpamTraining2019/pull/102/commits/1332a59a60598fce9326d18fb206945da09dd6fe](https://github.com/DzmitrySlutskiy/EpamTraining2019/pull/102/commits/1332a59a60598fce9326d18fb206945da09dd6fe)
@ilya-shknaj 
@kulebin

**Comment by ilya-shknaj** [comment]
ok
