### ISSUE TITLE
HW 11.03.2019 Compound view @DzmitrySlutskiy

### ISSUE THREAD

**Issue by GrodFor** [DzmitrySlutskiy/EpamTraining2019#107]
@DzmitrySlutskiy 
https://github.com/GrodFor/EpamHomework2019/pull/4

**Comment by DzmitrySlutskiy** [comment]
@GrodFor check comments

**Comment by DzmitrySlutskiy** [comment]
@GrodFor reminder

**Comment by GrodFor** [comment]
@DzmitrySlutskiy 
https://github.com/GrodFor/EpamHomework2019/commit/2a2e3dae8a1715778a9d493eaa086e431d5e5f50

**Comment by DzmitrySlutskiy** [comment]
@GrodFor reviewed, please add screenshots

**Comment by GrodFor** [comment]
@DzmitrySlutskiy uploaded gif

![drawer](https://user-images.githubusercontent.com/28896195/55108634-0b5eb600-50e5-11e9-9136-0d80a9bee3cd.gif)

**Comment by DzmitrySlutskiy** [comment]
@GrodFor please pay attention to my comments!
I'll close this HW.
