### ISSUE TITLE
HW 04.03.19 android components@DzmitrySlutskiy

### ISSUE THREAD

**Issue by zhengelev** [DzmitrySlutskiy/EpamTraining2019#108]
[Pull request link](https://github.com/zhengelev/EpamTraining2019/pull/2)

**Comment by DzmitrySlutskiy** [comment]
@zhengelev please check few comments. Also please note, clean code and code alignment should be in place forever!

**Comment by DzmitrySlutskiy** [comment]
@zhengelev reminder
