### ISSUE TITLE
Homework 04.03 android components

### ISSUE THREAD

**Issue by witaless** [DzmitrySlutskiy/EpamTraining2019#109]
@egorikftp 

[Homework pull request](https://github.com/witaless/EpamTrainingHomeWork/pull/2)

**Comment by egorikftp** [comment]
@witaless 

HW ok)

Notes:
1. Please don't forget to remove all logs from code
2. Constants should be ` static final`
3. Don't create fragment directly with `new Fragment()`. For this case use static method `newInstance()`

**Comment by witaless** [comment]
@egorikftp Fixed in latest [commit](https://github.com/witaless/EpamTrainingHomeWork/pull/2/commits/5e0cf764c22cde75db6bf408d6fff130ff40b567)
