### ISSUE TITLE
Homework 14.03 recycler view @egorikftp 

### ISSUE THREAD

**Issue by DoTheMonkeyBusiness** [DzmitrySlutskiy/EpamTraining2019#111]
@egorikftp 

RecyclerView:
https://github.com/DoTheMonkeyBusiness/EpamAndroid/pull/6

@egorikftp when I change the screen rotation, the StudentWebService class is recreated and because of this the recycler does not save its state and errors occur.

**Comment by DoTheMonkeyBusiness** [comment]
@egorikftp I don't understand why, but when I go to the end of the list sometimes I get this error, help me fix it.

![Screenshot_1](https://user-images.githubusercontent.com/36794185/54878753-10500b00-4e42-11e9-8eba-8615b235de12.png)

**Comment by egorikftp** [comment]
@DoTheMonkeyBusiness I will check your homework soon and found the root problem

**Comment by DoTheMonkeyBusiness** [comment]
@egorikftp Why 3 and 2 here if it should be 2 and 1?

![image](https://user-images.githubusercontent.com/36794185/55141279-1e0bd600-514b-11e9-9ee3-8bb97479d9c0.png)

**Comment by egorikftp** [comment]
@DoTheMonkeyBusiness 

1. RecyclerView doesn't save state (I see that you don't register your application in a manifest). Also in the final project, you won't allow using Koin library. I suggest trying to make your web service as `singleton`
2. App crashes when I enter some text in `student name` and click `Ok`


About your crash above)
Please try to make this code and scroll to the bottom of recyclerview and you will see what's wrong with your behavior. 
![image](https://user-images.githubusercontent.com/16294951/55357133-f616cc80-54d4-11e9-85b7-1f9a2dacc4eb.png)

**Comment by DoTheMonkeyBusiness** [comment]
@egorikftp redid🙋‍♂️, now the app doesn't crash, but i'm don't understand this:
> RecyclerView doesn't save state (I see that you don't register your application in a manifest).

**Comment by egorikftp** [comment]
@DoTheMonkeyBusiness I mean, that you told that after a rotation change your web service recreate. After that, I suggested you use Koin library. Then you added this di library into your project, but your service still recreates, all data pass to recycler view once again. In this case scroll position not save after rotation.

**Comment by DoTheMonkeyBusiness** [comment]
@egorikftp Redid🙋‍♂️

**Comment by egorikftp** [comment]
@DoTheMonkeyBusiness Done successfully
