### ISSUE TITLE
HW 04_03 @DzmitrySlutskiy

### ISSUE THREAD

**Issue by AntonLiaskevich** [DzmitrySlutskiy/EpamTraining2019#112]
https://github.com/AntonLiaskevich/EPAM_HW/pull/2
https://github.com/AntonLiaskevich/EPAM_HW/pull/3

**Comment by DzmitrySlutskiy** [comment]
@AntonLiaskevich reviewed. Please don't forget about clean code rules

**Comment by DzmitrySlutskiy** [comment]
@AntonLiaskevich reminder

**Comment by DzmitrySlutskiy** [comment]
@AntonLiaskevich are you going to close old HW?

**Comment by AntonLiaskevich** [comment]
pls check

**Comment by DzmitrySlutskiy** [comment]
@AntonLiaskevich added few comments, read and try to understand the main points. This HW I'll close.
