### ISSUE TITLE
HW_04.03_android_components @DzmitrySlutskiy

### ISSUE THREAD

**Issue by berdnikovEV** [DzmitrySlutskiy/EpamTraining2019#115]
@DzmitrySlutskiy https://github.com/berdnikovEV/EpamHomework/pull/2

**Comment by berdnikovEV** [comment]
Broadcast Receiver doesn't work yet. Can't understand why. Tried to rework it several times, but couldn't do it in the end

**Comment by DzmitrySlutskiy** [comment]
@berdnikovEV you are using receiver wrong way! please read about it:
https://developer.android.com/guide/components/broadcasts?hl=en

I've reviewed your MR please check

**Comment by berdnikovEV** [comment]
@DzmitrySlutskiy 
Changes: https://github.com/berdnikovEV/EpamHomework/compare/8ce365739e390cf43f75da55b385cd1c1c4b695a...e347f200aee7ebc96ab7d0b6f0f427aeee1d270d

Pull request: 
https://github.com/berdnikovEV/EpamHomework/pull/2

**Comment by DzmitrySlutskiy** [comment]
@berdnikovEV who is salozhor? I can see a lot of commits from this dev
looks like broadcasts send normally but you forget about clean code rules. I won't write these notes again and again, please pay attention on it. Please rework whole code with Clean code rules and I'll close this HW

**Comment by DzmitrySlutskiy** [comment]
@berdnikovEV reminder

**Comment by DzmitrySlutskiy** [comment]
@berdnikovEV are you going to close old HW?

**Comment by DzmitrySlutskiy** [comment]
@berdnikovEV reminder

**Comment by ilya-shknaj** [comment]
@berdnikovEV please don't ignore comments dzmitry. If you will not finish all homeworks, you will can't protect final project

**Comment by berdnikovEV** [comment]
> @berdnikovEV who is salozhor? I can see a lot of commits from this dev
> looks like broadcasts send normally but you forget about clean code rules. I won't write these notes again and again, please pay attention on it. Please rework whole code with Clean code rules and I'll close this HW

It's my initial github account. I had issues with bitbucket sign-in system. 
I had a lot of work in university, which had to be done, so i couldn't try and correct my previous HWs. RN everything is fine and I'm going to finish them asap. Thanks for patience.

**Comment by DzmitrySlutskiy** [comment]
@berdnikovEV 
But you have to understand that no-one will postpone whole training for you. It means that training will be done without you. Please plan your time properly. You have time before last thematic lecture to finish all HWs (24/04/19). After that you will be excluded. At the same time do not forget about whole goal of the training - final project which you have to present. Final project it is something more complex that home tasks and must include multiple screens with cache and image loading and so on.
