### ISSUE TITLE
Homework 11.03 navigation drawer compound view

### ISSUE THREAD

**Issue by witaless** [DzmitrySlutskiy/EpamTraining2019#126]
@egorikftp 

[HW Pull request](https://github.com/witaless/EpamTrainingHomeWork/pull/3)

**Comment by egorikftp** [comment]
@witaless Please fix issues and notify me

**Comment by witaless** [comment]
@egorikftp Please, check latest [commit](https://github.com/witaless/EpamTrainingHomeWork/pull/3/commits/048092fc980a7a4881df7b70177c47c740097e6f)

**Comment by egorikftp** [comment]
@witaless Done)
