### ISSUE TITLE
HW 06.03.19 view components

### ISSUE THREAD

**Issue by zhengelev** [DzmitrySlutskiy/EpamTraining2019#134]
[homework link](https://github.com/zhengelev/EpamTraining2019/pull/4) @DzmitrySlutskiy 
Screenshots made on tablet

![Screenshot_20190320-112458](https://user-images.githubusercontent.com/47432399/54784278-7bc48d80-4c34-11e9-8764-29c394bcccf6.jpg)
![Screenshot_20190321-233236](https://user-images.githubusercontent.com/47432399/54784279-7bc48d80-4c34-11e9-918b-c45a0f600d21.jpg)
![Screenshot_20190321-233557](https://user-images.githubusercontent.com/47432399/54784280-7c5d2400-4c34-11e9-9bd8-5fc4b80fe9c2.jpg)
![Screenshot_20190321-233828](https://user-images.githubusercontent.com/47432399/54784281-7c5d2400-4c34-11e9-9986-1b29aee41f0c.jpg)

**Comment by DzmitrySlutskiy** [comment]
@zhengelev nice to see that practically there is no any overdraw! at the same time please pay attention to task, there are a lot of issues with final result. For eg/ bottom view is not in bottom of the screen, no gaps between Photo 15 and Whats new? 
Also I can't see screens for google podcast.

**Comment by zhengelev** [comment]
Changes made.
![Screenshot_20190325-021422](https://user-images.githubusercontent.com/47432399/54887407-cf88de00-4ea3-11e9-859e-9594686b66c3.jpg)

![Screenshot_20190325-020049](https://user-images.githubusercontent.com/47432399/54887334-f266c280-4ea2-11e9-9642-50f2327bd198.jpg)
![Screenshot_20190325-020140](https://user-images.githubusercontent.com/47432399/54887335-f266c280-4ea2-11e9-9a66-5cea54101f1f.jpg)
![Screenshot_20190325-020206](https://user-images.githubusercontent.com/47432399/54887336-f2ff5900-4ea2-11e9-9248-972b1222b763.jpg)

**Comment by DzmitrySlutskiy** [comment]
there are still few gaps in layout but I'll close this HW. Please pay attention to other HW. A lot of them still need to do and fix 2 old
