### ISSUE TITLE
HW 06.03.19 @DzmitrySlutskiy

### ISSUE THREAD

**Issue by AntonLiaskevich** [DzmitrySlutskiy/EpamTraining2019#136]
https://github.com/AntonLiaskevich/EPAM_HW/pull/4
https://github.com/AntonLiaskevich/EPAM_HW/pull/5
https://github.com/DzmitrySlutskiy/EpamTraining2019/pull/135

**Comment by DzmitrySlutskiy** [comment]
@AntonLiaskevich 

for all these subtasks:

attach result screenshot
attach screenshot with enable Show layout bounds
attach screenshot with enable Debug GPU overdraw

screenshot which attached in google podcast it is something weird:)

**Comment by DzmitrySlutskiy** [comment]
@AntonLiaskevich reminder

**Comment by AntonLiaskevich** [comment]
I will do it tomorrow
Some problems with my laptop


пн, 1 апр. 2019 г., 22:08 DzmitrySlutskiy <notifications@github.com>:

**Comment by AntonLiaskevich** [comment]
check pls

**Comment by DzmitrySlutskiy** [comment]
@AntonLiaskevich As I can see in old links code was not changed and I still can't find screenshots.

**Comment by AntonLiaskevich** [comment]
check pls
also I added few comments to your commits

**Comment by DzmitrySlutskiy** [comment]
@AntonLiaskevich I left few new comments. But will close this HW. Please always pay attention to chain calls of the same method, naming and so on. It is ok while it is HW but in future it will be blocked on code review state.
