### ISSUE TITLE
Homework 18.03 kotlin @egorikftp 

### ISSUE THREAD

**Issue by DoTheMonkeyBusiness** [DzmitrySlutskiy/EpamTraining2019#139]
@egorikftp 

Kotkin-Koans:
https://github.com/DzmitrySlutskiy/EpamTraining2019/pull/138

**Comment by ilya-shknaj** [comment]
@DoTheMonkeyBusiness please fix AdditionalTest.kt

**Comment by DoTheMonkeyBusiness** [comment]
@ilya-shknaj I don't understand what is happening in this test ,it checks the presence of elements in the set, and works only if comment the constructor.

![image](https://user-images.githubusercontent.com/36794185/56494493-21e90900-64fb-11e9-9b47-40df7789cd06.png)

**Comment by DoTheMonkeyBusiness** [comment]
@ilya-shknaj fixed🙋‍♂️

**Comment by ilya-shknaj** [comment]
Good
