### ISSUE TITLE
hw_11.03_navigation_drawer

### ISSUE THREAD

**Issue by TashaB1** [DzmitrySlutskiy/EpamTraining2019#142]
@ilya-shknaj 

https://github.com/TashaB1/HomeWork/pull/6

![Screenshot_1553432408](https://user-images.githubusercontent.com/16763262/54879778-fc120b00-4e4d-11e9-8398-e3a6870fbec0.png)

**Comment by ilya-shknaj** [comment]
Ok, just few comments not related to current homework, but please take them into account

**Comment by TashaB1** [comment]
@ilya-shknaj 
fix few comment: https://github.com/TashaB1/HomeWork/compare/a99e8c8...hw1103navigationdrawer
![hw1103](https://user-images.githubusercontent.com/16763262/55837711-d746b480-5b2a-11e9-91e7-beac91571b1b.gif)
