### ISSUE TITLE
HW 11.03.19 NavigationDrawer @DzmitrySlutskiy

### ISSUE THREAD

**Issue by zhengelev** [DzmitrySlutskiy/EpamTraining2019#150]
![Screenshot_20190326-095947](https://user-images.githubusercontent.com/47432399/54977409-4ca07a00-4fae-11e9-945c-10058100c376.jpg)
![Screenshot_20190326-100030](https://user-images.githubusercontent.com/47432399/54977410-4ca07a00-4fae-11e9-95ea-6a0f5ed9ce1f.jpg)
@DzmitrySlutskiy

**Comment by zhengelev** [comment]
[Pull Request](https://github.com/zhengelev/EpamTraining2019/pull/5)

**Comment by DzmitrySlutskiy** [comment]
@zhengelev you forgot about link:)

**Comment by DzmitrySlutskiy** [comment]
ok, good

**Comment by DzmitrySlutskiy** [comment]
@zhengelev reviewed. Please pay attention to clean code rules, code/formating etc and comments, of course.

**Comment by DzmitrySlutskiy** [comment]
@zhengelev any updates?
