### ISSUE TITLE
 Homework 14.03 recycler view

### ISSUE THREAD

**Issue by witaless** [DzmitrySlutskiy/EpamTraining2019#167]
@egorikftp 
[HW pull](https://github.com/DzmitrySlutskiy/EpamTraining2019/pull/166)
[Screenshots](https://github.com/witaless/EpamTraining2019/commit/e4a1120d16ad08705e8ce80173398722491a3026)

**Comment by ilya-shknaj** [comment]
@witaless I can't open screenshoots via provided link in browser. 
I see that you add screenshoots into assets folder. In this case screenshoot will be in result apk file what's wrong. Please add it to root of project or create some folder which don't including into apk

**Comment by witaless** [comment]
@ilya-shknaj Sorry, but this assets folder is already in root of project, not in app folder. 
![assets folder sreenshot](https://user-images.githubusercontent.com/36520861/56420221-d1c53900-62a5-11e9-871e-4a2be7a9af3e.png)

<details> 
<summary><b>Sreenshoots also can be found here</b></summary>

Add new student
![recycler_view_add_new](https://user-images.githubusercontent.com/36520861/56420553-16050900-62a7-11e9-99e4-22f7d0d62b10.jpg)
Edit student
![recycler_view_edit_existed](https://user-images.githubusercontent.com/36520861/56420554-16050900-62a7-11e9-82e1-0b35d58fc05a.jpg)
RecyclerView
![recycler_view](https://user-images.githubusercontent.com/36520861/56420555-16050900-62a7-11e9-8fd8-97838334b1c6.jpg)
</details>

**Comment by ilya-shknaj** [comment]
sorry, assets folder name a bit confuse me, because android project also can have it

**Comment by ilya-shknaj** [comment]
Ok, good
