### ISSUE TITLE
homework_28.02_clean_code @kulebin

### ISSUE THREAD

**Issue by MaximSemashko** [DzmitrySlutskiy/EpamTraining2019#18]
Part 1:
MaximSemashko/android-calculator#1
Part 2:
#16
@kulebin

**Comment by kulebin** [comment]
reviewed, waiting for issues fixing

**Comment by MaximSemashko** [comment]
@kulebin 
Fixed issues
Part 1: 
https://github.com/MaximSemashko/android-calculator/pull/1/commits/7e10940f234e083cdf79b272101c22149f0fa83e
Part 2:
https://github.com/DzmitrySlutskiy/EpamTraining2019/pull/16/commits/0c383fe99bb9f060947356d933ab985797eb9f34

**Comment by kulebin** [comment]
reviewed
