### ISSUE TITLE
Homework 18.04 kotlin

### ISSUE THREAD

**Issue by witaless** [DzmitrySlutskiy/EpamTraining2019#180]
@egorikftp 
[HW Pull Request](https://github.com/DzmitrySlutskiy/EpamTraining2019/pull/179)

**Comment by ilya-shknaj** [comment]
@witaless N03DefaultArgumentsKtTest and AdditionalTest are failing. Please fix them

**Comment by witaless** [comment]
@ilya-shknaj Please, check latest [commit](https://github.com/DzmitrySlutskiy/EpamTraining2019/pull/179/commits/e02ff825e6160248883fdb5d66b2019767b0345b)

**Comment by ilya-shknaj** [comment]
@witaless Good. Just one tip from my side
