### ISSUE TITLE
Hw 18.04 kotlin @DzmitrySlutskiy

### ISSUE THREAD

**Issue by GrodFor** [DzmitrySlutskiy/EpamTraining2019#188]
@DzmitrySlutskiy 
https://github.com/GrodFor/EpamTraining2019/pull/3

**Comment by DzmitrySlutskiy** [comment]
@GrodFor reviewed, please fix small comment and I'll close this HW

**Comment by GrodFor** [comment]
@DzmitrySlutskiy 
https://github.com/GrodFor/EpamTraining2019/commit/7d84bae11478da19c45f7956f140f919d12d238b
