### ISSUE TITLE
Hw 14.03.2019 recycler view @DzmitrySlutskiy 

### ISSUE THREAD

**Issue by GrodFor** [DzmitrySlutskiy/EpamTraining2019#189]
@DzmitrySlutskiy
https://github.com/GrodFor/EpamTraining2019/pull/4 

![](https://user-images.githubusercontent.com/28896195/55279727-bf05b700-532c-11e9-8051-26af3d656a71.png)

![](https://user-images.githubusercontent.com/28896195/55279726-bf05b700-532c-11e9-804a-c2ddf3b690f1.png)

**Comment by DzmitrySlutskiy** [comment]
@GrodFor reviewed, please check comments

**Comment by GrodFor** [comment]
@DzmitrySlutskiy 
https://github.com/GrodFor/EpamTraining2019/commit/43e47144b4799ffbb8f686a55a56f3743387f57c
