### ISSUE TITLE
Incorrect displaying items in recycler view

### ISSUE THREAD

**Issue by AliakseiShvants** [DzmitrySlutskiy/EpamTraining2019#200]
CC: @ilya-shknaj @egorikftp 
https://github.com/AliakseiShvants/RunningLife/tree/fragments
1) When item in recycler view doesn't have an image, it width isn't 'match_parent'
![screenshot-2019-04-26_11 07 59 709](https://user-images.githubusercontent.com/20282769/56793431-51a25480-680c-11e9-95e5-ec028886bb87.png)
2)  First time recycler displays first and second item incorrectly, but after scrolling down-up there's in normal state
https://drive.google.com/file/d/1hzhBMrEqAQ4-XWCoCQDXkEqHw7aNjMyH/view?usp=sharing

**Comment by ilya-shknaj** [comment]
@AliakseiShvants Did you try to fix it this way https://stackoverflow.com/questions/24503760/cardview-layout-width-match-parent-does-not-match-parent-recyclerview-width?

If it will not work, please push gradle folder to git, because I can't just clone and run your project

**Comment by DzmitrySlutskiy** [comment]
@AliakseiShvants first of all make sure your project is compilable. I've done a lot of manipulations to fix project's issues.
Here main fix of your issue!:
` if (viewType == ViewType.MOVE) {
            //return new ViewHolder(new RunMoveView(parent.getContext()));
            return new ViewHolder(inflater.inflate(R.layout.adapter_item_run_move, parent, FALSE));
        } else {
            return new ViewHolder(inflater.inflate(R.layout.layout_progress, parent, FALSE));
        }`

Pay attention to how you are going to create your views for RecyclerView. Always do inflating and pass parent into inflate method. This parameter will help this view to measure self properly!

adapter item is pretty simple:
`<com.shvants.runninglife.ui.view.RunMoveView xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical" android:layout_width="match_parent"
    android:layout_height="wrap_content">

</com.shvants.runninglife.ui.view.RunMoveView>`

Also I've found few issues, you do not save item's state, if I press to item and will scroll the expanded state will be applied to any "random" item and when I arrive back to expanded item it will be in unknown state (may be expanded may be not, depends on God, stars, Moon and so on :))

**Comment by AliakseiShvants** [comment]
Thanks for help!

вс, 28 апр. 2019 г. в 21:27, DzmitrySlutskiy <notifications@github.com>:

**Comment by DzmitrySlutskiy** [comment]
@AliakseiShvants please close issue if your issue resolved
