### ISSUE TITLE
HW_24.03_Gradle @kulebin

### ISSUE THREAD

**Issue by wanderer005** [DzmitrySlutskiy/EpamTraining2019#201]
Homework 24.03 gradle
[https://github.com/wanderer005/FlavorsTest/pull/1](https://github.com/wanderer005/FlavorsTest/pull/1)
@kulebin

**Comment by kulebin** [comment]
@wanderer005 reviewed, please fix mentioned issues in your pull request.

**Comment by kulebin** [comment]
all issues fixed.
