### ISSUE TITLE
HW_Git @kulebin

### ISSUE THREAD

**Issue by AlexGolovach** [DzmitrySlutskiy/EpamTraining2019#203]
https://github.com/AlexGolovach/GitTask/compare/8eb3a6677ff7af197f23862e3f02b4f721b18857...fcd5aa30fc8b843bf8064aa2b1471e093d88af10

cherry pick: https://github.com/AlexGolovach/GitTask/commit/7c2a131040884d29e838833742a53bfeddea5aab
conflict: https://github.com/AlexGolovach/GitTask/commit/246332290badbb4e213f396df22164c9888125a3
submodule: https://github.com/AlexGolovach/GitTask/commit/3365e3031f8c747cb940cb0ce7a32d6fd2c627ab
@kulebin

**Comment by ilya-shknaj** [comment]
ok
