### ISSUE TITLE
hw_28.02.19_clean_code @ilya-shknaj

### ISSUE THREAD

**Issue by Kirazavrik** [DzmitrySlutskiy/EpamTraining2019#27]
@ilya-shknaj 

Part 1:
https://github.com/Kirazavrik/SimpleCalculator/pull/1

Part 2:
https://github.com/DzmitrySlutskiy/EpamTraining2019/pull/26

**Comment by ilya-shknaj** [comment]
@Kirazavrik could you say your name? I can't find you in list

**Comment by Kirazavrik** [comment]
@ilya-shknaj  ALIEKSANDR ZAKHARCHANKA

**Comment by ilya-shknaj** [comment]
@Kirazavrik what about first git homework ? I don't found issue

**Comment by ilya-shknaj** [comment]
@Kirazavrik reviewed. Please fix my comments

**Comment by Kirazavrik** [comment]
@ilya-shknaj fixed. Please check it.

**Comment by ilya-shknaj** [comment]
ok
