### ISSUE TITLE
HW clean_code

### ISSUE THREAD

**Issue by kirylshreyter** [DzmitrySlutskiy/EpamTraining2019#28]
@ilya-shknaj 

part I:
https://github.com/kirylshreyter/calculator/pull/5

part II:
https://github.com/DzmitrySlutskiy/EpamTraining2019/pull/32

**Comment by kirylshreyter** [comment]
@ilya-shknaj 
The second part of HW was added.

**Comment by ilya-shknaj** [comment]
reviewed. Please fix my comments

**Comment by kirylshreyter** [comment]
@ilya-shknaj 
both parts are fixed

**Comment by ilya-shknaj** [comment]
Good
