### ISSUE TITLE
HW 28.02_clean_code @egorikftp

### ISSUE THREAD

**Issue by AlekseichukA** [DzmitrySlutskiy/EpamTraining2019#30]
part1
[](https://github.com/AlekseichukA/PinkCalculator/pull/1)

part2
[](https://github.com/DzmitrySlutskiy/EpamTraining2019/pull/29)

**Comment by AlekseichukA** [comment]
part1
[calculator](https://github.com/AlekseichukA/PinkCalculator/pull/1)
part2
[#29](https://github.com/DzmitrySlutskiy/EpamTraining2019/pull/29)

**Comment by egorikftp** [comment]
Please fix issues in merge requests and notify me after that.

**Comment by egorikftp** [comment]
@AlekseichukA 
Part 1. Some code style issues.
Part 2. Small issues about naming. Other things - good

**Comment by AlekseichukA** [comment]
I corrected your comments

**Comment by ilya-shknaj** [comment]
@AlekseichukA please fix issues founded by me as well. 
Also please notify Yahor over '@egorikftp' when you fix all issues

**Comment by egorikftp** [comment]
@AlekseichukA any updates?

**Comment by AlekseichukA** [comment]
I update programs

**Comment by egorikftp** [comment]
@AlekseichukA 

Part 1: @ilya-shknaj, please clarify your commentary

Part 2: small issues

**Comment by AlekseichukA** [comment]
I corrected issues

**Comment by ilya-shknaj** [comment]
@egorikftp ok from my side

**Comment by egorikftp** [comment]
@AlekseichukA Clean code part 2 😪 Please be careful

**Comment by AlekseichukA** [comment]
I returned function haveValidParameters
