### ISSUE TITLE
Clean code HW_28_02 @DzmitrySlutskiy

### ISSUE THREAD

**Issue by zhengelev** [DzmitrySlutskiy/EpamTraining2019#34]
[Part 1](https://github.com/zhengelev/Calculator/pull/1)
[Part 2](https://github.com/DzmitrySlutskiy/EpamTraining2019/pull/33)

**Comment by DzmitrySlutskiy** [comment]
@zhengelev please check comments

**Comment by DzmitrySlutskiy** [comment]
@zhengelev submitted review, please check

**Comment by ilya-shknaj** [comment]
@zhengelev reminder

**Comment by DzmitrySlutskiy** [comment]
@zhengelev any updates on clean code HW?

**Comment by DzmitrySlutskiy** [comment]
@zhengelev reminder

**Comment by DzmitrySlutskiy** [comment]
@zhengelev reminder

**Comment by ilya-shknaj** [comment]
@zhengelev you have to finish this homework if you want to finish Android training. If you don't done all homeworks, we can't give you сertificate. 
Deadline for all homeworks is end of this week, otherwise we will have to dismiss you.
