### ISSUE TITLE
homework 04.03 @ilya-shknaj

### ISSUE THREAD

**Issue by aliakseikanapeshka** [DzmitrySlutskiy/EpamTraining2019#35]
@ilya-shknaj

https://github.com/aleksei-kon/HomeWork/pull/1

**Comment by ilya-shknaj** [comment]
@aleksei-kon reviewed. Please fix my comments

**Comment by aliakseikanapeshka** [comment]
@ilya-shknaj 

Fixed. Please check two last commits https://github.com/aleksei-kon/HomeWork/pull/1

**Comment by ilya-shknaj** [comment]
ok. Please don't forget update gitignore file. Next time I will ask you to remove all unnecessary files. If not clear how to detect which files should be ignore, please ask about it on lecture
