### ISSUE TITLE
HomeWork 28.02 clean code @kulebin

### ISSUE THREAD

**Issue by wanderer005** [DzmitrySlutskiy/EpamTraining2019#36]
part1
[part1](https://github.com/wanderer005/BasicCalculator/commit/e97ca16e941fa70540c2a9ea90219c6079f3da90)
part2
[part2](https://github.com/DzmitrySlutskiy/EpamTraining2019/pull/12/commits/0883f21501385de52342e4eefe1d15c829870ea1)

@kulebin

**Comment by kulebin** [comment]
@wanderer005 pls fix all issues in  https://github.com/wanderer005/BasicCalculator/commit/e97ca16e941fa70540c2a9ea90219c6079f3da90

**Comment by wanderer005** [comment]
Thank you for review.
Commit with fixes:
[https://github.com/wanderer005/BasicCalculator/commit/07328d289e3dabf01a4ff1d0708772dde2082250](https://github.com/wanderer005/BasicCalculator/commit/07328d289e3dabf01a4ff1d0708772dde2082250)

@kulebin

**Comment by wanderer005** [comment]
Thanks for review
Commit with fixes:
[https://github.com/wanderer005/BasicCalculator/commit/71319300881ce11942617b1048ea9e4d0293100b](https://github.com/wanderer005/BasicCalculator/commit/71319300881ce11942617b1048ea9e4d0293100b)

@kulebin

**Comment by ilya-shknaj** [comment]
@wanderer005 Please create pull request and update links. In this pull request we should see changes related to homework and if you will fix some our comment it automatically update

**Comment by wanderer005** [comment]
Thanks for review.
Pull request 
[https://github.com/wanderer005/BasicCalculator/pull/3](https://github.com/wanderer005/BasicCalculator/pull/3)

@kulebin 
@ilya-shknaj

**Comment by kulebin** [comment]
@wanderer005 please fix last issue

**Comment by kulebin** [comment]
checked
