### ISSUE TITLE
HomeWork 04.03 @kulebin

### ISSUE THREAD

**Issue by wanderer005** [DzmitrySlutskiy/EpamTraining2019#37]
[HW 04.03](https://github.com/wanderer005/Hw_04.03.2019/issues/1)

@kulebin

**Comment by wanderer005** [comment]
Please, mark my home work yellow done (because of deadline requirements)

@kulebin

**Comment by wanderer005** [comment]
HW 04.03 review fixes (not sure if I needed to make a separate branch for fixes, so I push it in master)

[https://github.com/wanderer005/Hw_04.03.2019/commit/9b29c16eca6e5341ec4b4cd12652bce978fffa26](https://github.com/wanderer005/Hw_04.03.2019/commit/9b29c16eca6e5341ec4b4cd12652bce978fffa26)

@kulebin

**Comment by kulebin** [comment]
reviewed
