### ISSUE TITLE
homework 04.03 android components @egorikftp 

### ISSUE THREAD

**Issue by DoTheMonkeyBusiness** [DzmitrySlutskiy/EpamTraining2019#42]
@egorikftp 

Part 1:
https://github.com/DoTheMonkeyBusiness/EpamAndroid/pull/1

Part 2:
https://github.com/DoTheMonkeyBusiness/EpamAndroid/pull/2

And look the changes in the past homework: 
https://github.com/DzmitrySlutskiy/EpamTraining2019/issues/9

**Comment by egorikftp** [comment]
@DoTheMonkeyBusiness I can't build your project, because you don't have any classes inside `mysubmodule`.
I suggest adding library module instead git submodule

**Comment by DoTheMonkeyBusiness** [comment]
@egorikftp git submodule it's part of my first homework. There was a conflict in my project because I made a correction in the master branch and didn't take this into in the pull request 😬

**Comment by egorikftp** [comment]
Part 1: Text inside this button not saved after orientation change. 

![image](https://user-images.githubusercontent.com/16294951/54492247-ec3a7a00-48d5-11e9-8db3-80660b020538.png)

Part 2:
1. Branch name should contain single `_` 
![image](https://user-images.githubusercontent.com/16294951/54492812-c2378680-48da-11e9-9362-f182c09fe138.png)
2. If I rotate device during gif animation, then I will see only color animation. Also I can't stop service in this case. 

![image](https://user-images.githubusercontent.com/16294951/54493308-7affc480-48df-11e9-8b2e-013758defd12.png)

Please fix all issues and comments, then notify me.

**Comment by DoTheMonkeyBusiness** [comment]
@egorikftp redid.

**Comment by egorikftp** [comment]
@DoTheMonkeyBusiness 

Part 1 - good
Part 2 - good

🙂
