### ISSUE TITLE
HW_git @DzmitrySlutskiy

### ISSUE THREAD

**Issue by GrodFor** [DzmitrySlutskiy/EpamTraining2019#43]
https://github.com/GrodFor/EpamHomework2019/compare/feature_2...master
Conflict: https://github.com/GrodFor/EpamHomework2019/commit/dc04935edbafdf7b57f1c298ffed4a15a377afa3
Cherry pick: https://github.com/GrodFor/EpamHomework2019/compare/master...feature_3
@DzmitrySlutskiy

**Comment by DzmitrySlutskiy** [comment]
@GrodFor good. Issue closed
