### ISSUE TITLE
HW 28.02 clean code @DzmitrySlutskiy 

### ISSUE THREAD

**Issue by GrodFor** [DzmitrySlutskiy/EpamTraining2019#44]
Part 1: https://github.com/GrodFor/Andro-calc/pull/1
@DzmitrySlutskiy

**Comment by GrodFor** [comment]
Part 2: https://github.com/GrodFor/EpamTraining2019/pull/1

**Comment by DzmitrySlutskiy** [comment]
@GrodFor sorry for delay, looks like I missed it. Please check my comments

**Comment by DzmitrySlutskiy** [comment]
@GrodFor any updates on clean code HW?

**Comment by GrodFor** [comment]
@DzmitrySlutskiy 
1. https://github.com/GrodFor/Andro-calc/commit/c2c5b486c7f343392083076e2c9cbc3ca11a2892
2. https://github.com/GrodFor/EpamTraining2019/commit/4c40bc97e89940f5da7f97d19a0f0c6f754b04f4

**Comment by DzmitrySlutskiy** [comment]
@GrodFor p.1 new comments
p.2 ok, just one comment, operations has common naming, add/sub/mult! not product

**Comment by GrodFor** [comment]
@DzmitrySlutskiy 
1. https://github.com/GrodFor/Andro-calc/commit/c6eade9eaea3135eca9c4f9d3074ac40fb4e3c89

**Comment by DzmitrySlutskiy** [comment]
@GrodFor closed HW, please pay attention to other tasks, dead line still exists
