### ISSUE TITLE
HW Clean code @ilya-shknaj

### ISSUE THREAD

**Issue by TashaB1** [DzmitrySlutskiy/EpamTraining2019#46]
@ilya-shknaj
Calculate https://github.com/TashaB1/calculate/commit/98bad90febd723b26903f0f137c49a4f320276ec 
Clean code https://github.com/DzmitrySlutskiy/EpamTraining2019/pull/45

**Comment by ilya-shknaj** [comment]
Looks good. Please fix few my comments

**Comment by TashaB1** [comment]
@ilya-shknaj 
Clean code fix https://github.com/TashaB1/EpamTraining2019/commit/e2848c1f5ec0ec7697069142242c0daa4c532733
Calculate https://github.com/TashaB1/calculate/commit/2973a42154e260cbf68bba695a77ceac836f66c3

**Comment by ilya-shknaj** [comment]
Good
