### ISSUE TITLE
HW git

### ISSUE THREAD

**Issue by kirylshreyter** [DzmitrySlutskiy/EpamTraining2019#5]
https://github.com/kirylshreyter/instagramclient/compare/00aa31b41464faa902d51c6d889f943b61b1b956...bb52924226c1b605c03679e7ffcbcbf7ee635f84
@ilya-shknaj

**Comment by ilya-shknaj** [comment]
@kirylshreyter 
I didn't found any conflicts in commits https://github.com/kirylshreyter/instagramclient/commit/420e386bae41f9eaf1360eb0439e6bd2666a8c92

https://github.com/kirylshreyter/instagramclient/commit/c093c3195240d6d653051019cc1b88c76e270663
Please try to create and resolve conflicts one more time.
How to do it :
Implement some functionality in branch1. Then reimplement it in branch1 and branch2 and after that merge result from both branches.

As result commit message should have something like this
https://github.com/DzmitrySlutskiy/EpamTraining2019/commit/8ebbd3593cb192c97f83558449a5750894ab126d
and I should see some changes.

Also please provide link to commit where you tryied rebase.

**Comment by kirylshreyter** [comment]
@ilya-shknaj 

The cause of you hadn't saw conflicts is that I'm currently using git via command line and forgot to set **--no-edit** flag, so git has not added the proper comment to the commit. This was fixed here:
https://github.com/kirylshreyter/diamondapp/commit/068a81592a2d2500cf4471f115b3b30dff3b140e

In this PR you could see that I've force pushed after doing rebase with master:
https://github.com/kirylshreyter/diamondapp/pull/3

Thanks.
