### ISSUE TITLE
HW_06.03Part_1 @ajaxspace

### ISSUE THREAD

**Issue by AndreyIIT4** [DzmitrySlutskiy/EpamTraining2019#60]
[HW_06.03_part_1](https://github.com/AndreyIIT4/AndroidView.git)
[Screen](https://github.com/AndreyIIT4/AndroidView/blob/master/app/src/main/res/mipmap-mdpi/ScreenshotVkProfile.png)

**Comment by ajaxspace** [comment]
Provide link only on changes to check instead of link to repository. Also fix .gitignore (.idea folder)

**Comment by ilya-shknaj** [comment]
Good bye and good luck
