### ISSUE TITLE
HW 04.03.2019 android_components @DzmitrySlutskiy

### ISSUE THREAD

**Issue by GrodFor** [DzmitrySlutskiy/EpamTraining2019#67]
https://github.com/GrodFor/EpamHomework2019/compare/hw_04.03.2019_android_components
@DzmitrySlutskiy

**Comment by DzmitrySlutskiy** [comment]
@GrodFor see my comments

**Comment by GrodFor** [comment]
@DzmitrySlutskiy 
Sorry, but I can't find any comments.

**Comment by DzmitrySlutskiy** [comment]
@GrodFor because I left them in your pull request here https://github.com/GrodFor/EpamHomework2019/pull/2

check the way how you create link. I'm not able to comment in your compare link

**Comment by GrodFor** [comment]
@DzmitrySlutskiy Still can't see anything

![2019-03-12 21-56-38 Hw 04 03 2019 android components by GrodFor · Pull Request #2 · GrodFor EpamHomework2019 - Google Chrom](https://user-images.githubusercontent.com/28896195/54227979-2e4c7000-4512-11e9-8de4-694669a1f709.png)


![2019-03-12 21-58-42 Hw 04 03 2019 android components by GrodFor · Pull Request #2 · GrodFor EpamHomework2019 - Google Chrom](https://user-images.githubusercontent.com/28896195/54227954-1f65bd80-4512-11e9-9fbe-b442c4c01b1e.png)

**Comment by DzmitrySlutskiy** [comment]
@GrodFor I've submitted review.

**Comment by DzmitrySlutskiy** [comment]
@GrodFor any updates?

**Comment by DzmitrySlutskiy** [comment]
@GrodFor reminder

**Comment by GrodFor** [comment]
@DzmitrySlutskiy 
https://github.com/GrodFor/EpamHomework2019/commit/1e86af6aa5f75428e6f5d3b842067689d413f62b

**Comment by DzmitrySlutskiy** [comment]
@GrodFor good, I'll close this HW
