### ISSUE TITLE
HW 28.02

### ISSUE THREAD

**Issue by berdnikovEV** [DzmitrySlutskiy/EpamTraining2019#75]
Part 1:
https://github.com/berdnikovEV/EpamAndroidTrainingCalculator/compare/master...CleanCode
Part 2:
https://github.com/DzmitrySlutskiy/EpamTraining2019/pull/74

@DzmitrySlutskiy

**Comment by DzmitrySlutskiy** [comment]
@berdnikovEV could you please create pull request for part 1. I can't leave comment in code

**Comment by berdnikovEV** [comment]
@DzmitrySlutskiy  https://github.com/berdnikovEV/EpamAndroidTrainingCalculator/pull/1

**Comment by DzmitrySlutskiy** [comment]
@berdnikovEV please check comments

**Comment by berdnikovEV** [comment]
@DzmitrySlutskiy I don't see any comments on any of the provided links

**Comment by DzmitrySlutskiy** [comment]
@berdnikovEV are you serious? check pull request https://github.com/berdnikovEV/EpamAndroidTrainingCalculator/pull/1

you've posted 2 links. 
Part 1 designed with old HW flow with compare and this one I can't leave comments
Part 2 designed by new HW flow and I left at least 4 comments.
Please use new flow described in https://github.com/DzmitrySlutskiy/EpamTraining2019 readme file: 
Homework flow:
Issues should be created in this repository!
Make homework in separate branch with following format: homework_DD.MM_theme_name (homework_28.02_clean_code)
Open pull request in you repository and provide link in issue.

**Comment by DzmitrySlutskiy** [comment]
@berdnikovEV any updates on clean code HW?

**Comment by DzmitrySlutskiy** [comment]
@berdnikovEV reminder

**Comment by DzmitrySlutskiy** [comment]
@berdnikovEV are you going to close old HW?

**Comment by DzmitrySlutskiy** [comment]
@berdnikovEV reminder

**Comment by ilya-shknaj** [comment]
@berdnikovEV your request was reviewed more that month ago. Please fix issues founded by @DzmitrySlutskiy or we will have to exclude you from training

**Comment by ilya-shknaj** [comment]
Goodbye
