### ISSUE TITLE
HW 06.03.2019 Anroid views @DzmitrySlutskiy

### ISSUE THREAD

**Issue by GrodFor** [DzmitrySlutskiy/EpamTraining2019#76]
@DzmitrySlutskiy 
Task 1: https://github.com/GrodFor/EpamTraining2019/pull/2

**Comment by DzmitrySlutskiy** [comment]
@GrodFor  reviewed. check comments

**Comment by GrodFor** [comment]
@DzmitrySlutskiy 
Task 1: https://github.com/GrodFor/EpamTraining2019/pull/2/commits/96947a6fb568a3acf1d8a75e3592e14244948965
Task 2:
https://github.com/GrodFor/EpamHomework2019/pull/3

**Comment by DzmitrySlutskiy** [comment]
@GrodFor 
#1 ok
#2 check comments and add screenshots

**Comment by GrodFor** [comment]
@DzmitrySlutskiy 
2. https://github.com/GrodFor/EpamHomework2019/commit/e20e52358e4e3ffcfe3f6840c51c3649eacd0a79
Screenshots: https://github.com/GrodFor/EpamHomework2019/pull/3/commits/661769e19ddec65c0807e71e5f56c473bc6b7dfb

**Comment by DzmitrySlutskiy** [comment]
some small comment, I close this issue
