### ISSUE TITLE
hw 06.03 views components

### ISSUE THREAD

**Issue by shjman** [DzmitrySlutskiy/EpamTraining2019#77]
@ajaxspace 

part1:
https://github.com/DzmitrySlutskiy/EpamTraining2019/pull/57

part2:

https://github.com/shjman/s/pull/3

**Comment by ajaxspace** [comment]
Part 1: Add mentor name for all available lessons (at least one more).

**Comment by shjman** [comment]
updated.remake. part 1 
(close issue is misclick,sorry)  
![Screenshot_first_task_updated](https://user-images.githubusercontent.com/31157882/54471895-73ea9080-47d1-11e9-9c40-6abbd9da87ac.png)

**Comment by shjman** [comment]
@ajaxspace 
and i want make MR from epamTraning-master to my (forked) epamTranin-master. for fetch  new changes from new lesson. and my home work will deleted? and this current MR with hw will be ugly?
