### ISSUE TITLE
HW_28.02_clean_code @DzmitrySlutskiy

### ISSUE THREAD

**Issue by AntonLiaskevich** [DzmitrySlutskiy/EpamTraining2019#81]
https://github.com/AntonLiaskevich/Calculator_Epam/pull/1
https://github.com/DzmitrySlutskiy/EpamTraining2019/pull/80

**Comment by DzmitrySlutskiy** [comment]
@AntonLiaskevich reviewed, please check and notify when some changes applied

**Comment by AntonLiaskevich** [comment]
done

**Comment by DzmitrySlutskiy** [comment]
@AntonLiaskevich reviewed. Please check new portion of comments

**Comment by DzmitrySlutskiy** [comment]
@AntonLiaskevich reminder

**Comment by AntonLiaskevich** [comment]
I did it 8 days ago)
I forgot to write about it here(

**Comment by DzmitrySlutskiy** [comment]
got it, closed
