### ISSUE TITLE
HW 04.03 android components @egorikftp

### ISSUE THREAD

**Issue by AlekseichukA** [DzmitrySlutskiy/EpamTraining2019#83]
[HW 03.03](https://github.com/DzmitrySlutskiy/EpamTraining2019/pull/82l)

**Comment by egorikftp** [comment]
Correct link: https://github.com/DzmitrySlutskiy/EpamTraining2019/pull/82

**Comment by egorikftp** [comment]
@AlekseichukA App works good, small remarks found
