### ISSUE TITLE
Homework 28.02.19 Clean_code @ajaxspace

### ISSUE THREAD

**Issue by AndreyIIT4** [DzmitrySlutskiy/EpamTraining2019#84]
[review ](https://github.com/AndreyIIT4/Calculator/issues/376100aa0706fd966e00a79bf5570dcec7e43234)
[HW 28.02 Clean code training Part 2](https://github.com/AndreyIIT4/Calculator/issues/874a44aad62072cbcea8b5814fca1dc3219d24ad)
@ajaxspace

**Comment by ilya-shknaj** [comment]
@AndreyIIT4 Looks like you leave from training by yourself. So, because of that I just close this homework. Please correct me if I'm wrong
