### ISSUE TITLE
Homework 11.03 navigation drawer @egorikftp 

### ISSUE THREAD

**Issue by DoTheMonkeyBusiness** [DzmitrySlutskiy/EpamTraining2019#86]
@egorikftp 
Navigation Drawer:
https://github.com/DoTheMonkeyBusiness/EpamAndroid/pull/5

**Comment by egorikftp** [comment]
@DoTheMonkeyBusiness It's not a joke. Why I need to comment this code in all of your homework before building project

![image](https://user-images.githubusercontent.com/16294951/54713983-f91ece00-4b60-11e9-8ac6-ec8e1e0f5018.png)

**Comment by egorikftp** [comment]
![image](https://user-images.githubusercontent.com/16294951/54714120-4ac75880-4b61-11e9-897a-61f04f9db7f0.png)
Color not saved after the device rotation

**Comment by egorikftp** [comment]
@DoTheMonkeyBusiness Homework is fully incorrect. I will explain tomorrow

**Comment by DoTheMonkeyBusiness** [comment]
@egorikftp redid🙋‍♂️

**Comment by egorikftp** [comment]
@DoTheMonkeyBusiness Done)
