### ISSUE TITLE
Homework 06.03 android ui

### ISSUE THREAD

**Issue by witaless** [DzmitrySlutskiy/EpamTraining2019#89]
@egorikftp 
[Part 1](https://github.com/DzmitrySlutskiy/EpamTraining2019/pull/88)
[Part 2](https://github.com/witaless/EpamTrainingHomeWork/pull/1)

**Comment by egorikftp** [comment]
Part 1 - ok

**Comment by egorikftp** [comment]
@witaless 
Part 2 - I think it's the most careful UI, good job 🙂 

Some notes:
1. Better to align XML for vector drawable

**Comment by witaless** [comment]
@egorikftp Fixed in latest [commit](https://github.com/witaless/EpamTrainingHomeWork/pull/1/commits/df9cdafde7acd0c9b01885f911c7064d21d4ef48)
