### ISSUE TITLE
Homework 28.02 clean code

### ISSUE THREAD

**Issue by witaless** [DzmitrySlutskiy/EpamTraining2019#91]
@egorikftp 
[Part 1](https://github.com/witaless/Calculator-epam-training/pull/1)
[Part 2](https://github.com/DzmitrySlutskiy/EpamTraining2019/pull/90)

**Comment by egorikftp** [comment]
@witaless Please fix issues in Part 1 and Part 2 and then notify me in this issue

**Comment by egorikftp** [comment]
@witaless any updates?

**Comment by witaless** [comment]
@egorikftp 
Sorry, some personal troubles, updates coming soon

**Comment by egorikftp** [comment]
@witaless Any updates?

**Comment by witaless** [comment]
@egorikftp 
Please, check my commits
[Part 1 fix](https://github.com/witaless/Calculator-epam-training/pull/1/commits/48d1e2fb108c42a942fa87a039b1d2855e8bf565)
[Part 2 fix](https://github.com/DzmitrySlutskiy/EpamTraining2019/pull/90/commits/dd4a1037e6b2ea73b6c4af8b18762ee61088d80e)
[Reason of delay](https://yadi.sk/i/8VDVarj85666wQ)

**Comment by egorikftp** [comment]
@witaless Good)
